/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.interfase;

import com.conversor.model.Moneda;
import com.formdev.flatlaf.FlatDarkLaf;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author nigeh
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupIn = new javax.swing.ButtonGroup();
        buttonGroupOut = new javax.swing.ButtonGroup();
        tituloLabel = new javax.swing.JLabel();
        inLabel = new javax.swing.JLabel();
        inText = new javax.swing.JTextField();
        tabPanel = new javax.swing.JTabbedPane();
        monedaTab = new javax.swing.JPanel();
        inMonedaLabel = new javax.swing.JLabel();
        outMonedaLabel = new javax.swing.JLabel();
        conversionMonedaLabel = new javax.swing.JLabel();
        resultadoMonedaLabel = new javax.swing.JLabel();
        conversionMonedaButon = new javax.swing.JButton();
        inMXN = new javax.swing.JRadioButton();
        inUSD = new javax.swing.JRadioButton();
        inEUR = new javax.swing.JRadioButton();
        inGBP = new javax.swing.JRadioButton();
        inJPY = new javax.swing.JRadioButton();
        inKRW = new javax.swing.JRadioButton();
        outMXN = new javax.swing.JRadioButton();
        outUSD = new javax.swing.JRadioButton();
        outEUR = new javax.swing.JRadioButton();
        outGBP = new javax.swing.JRadioButton();
        outJPY = new javax.swing.JRadioButton();
        outKRW = new javax.swing.JRadioButton();
        longTab = new javax.swing.JPanel();
        inLongLabel = new javax.swing.JLabel();
        outLongLabel = new javax.swing.JLabel();
        conversionLongLabel = new javax.swing.JLabel();
        resultadoLongLabel = new javax.swing.JLabel();
        conversionLongButon = new javax.swing.JButton();
        areaTab = new javax.swing.JPanel();
        inAreaLabel = new javax.swing.JLabel();
        outAreaLabel = new javax.swing.JLabel();
        conversionAreaLabel = new javax.swing.JLabel();
        resultadoAreaLabel = new javax.swing.JLabel();
        conversionAreaButon = new javax.swing.JButton();
        volTab = new javax.swing.JPanel();
        inVolLabel = new javax.swing.JLabel();
        outVolLabel = new javax.swing.JLabel();
        conversionVolLabel = new javax.swing.JLabel();
        resultadoVolLabel = new javax.swing.JLabel();
        conversionVolButon = new javax.swing.JButton();
        velTab = new javax.swing.JPanel();
        inVelLabel = new javax.swing.JLabel();
        outVelLabel = new javax.swing.JLabel();
        conversionVelLabel = new javax.swing.JLabel();
        resultadoVelLabel = new javax.swing.JLabel();
        conversionVelButon = new javax.swing.JButton();
        tempTab = new javax.swing.JPanel();
        inTempLabel = new javax.swing.JLabel();
        outTempLabel = new javax.swing.JLabel();
        conversionTempLabel = new javax.swing.JLabel();
        resultadoTempLabel = new javax.swing.JLabel();
        conversionTempButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ORDUS");
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Conversor");

        inLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        inLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inLabel.setText("Cantidad");

        inText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inText.setText("0.00");
        inText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inTextMouseClicked(evt);
            }
        });

        inMonedaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inMonedaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inMonedaLabel.setText("Moneda origen");

        outMonedaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outMonedaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outMonedaLabel.setText("Moneda destino");

        conversionMonedaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionMonedaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conversionMonedaLabel.setText("Conversión");

        resultadoMonedaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        resultadoMonedaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoMonedaLabel.setText("0.00");

        conversionMonedaButon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionMonedaButon.setText("Convertir");
        conversionMonedaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversionMonedaButonActionPerformed(evt);
            }
        });

        buttonGroupIn.add(inMXN);
        inMXN.setSelected(true);
        inMXN.setText("Peso mexicano (MXN)");
        inMXN.setActionCommand("MXN");

        buttonGroupIn.add(inUSD);
        inUSD.setText("Dólar estadounidense (USD)");
        inUSD.setActionCommand("USD");

        buttonGroupIn.add(inEUR);
        inEUR.setText("Euro (EUR)");
        inEUR.setActionCommand("EUR");

        buttonGroupIn.add(inGBP);
        inGBP.setText("Libra esterlina (GBP)");
        inGBP.setActionCommand("GBP");

        buttonGroupIn.add(inJPY);
        inJPY.setText("Yen japonés (JPY)");
        inJPY.setActionCommand("JPY");

        buttonGroupIn.add(inKRW);
        inKRW.setText("Won surcoreano (KRW)");
        inKRW.setActionCommand("KRW");

        buttonGroupOut.add(outMXN);
        outMXN.setSelected(true);
        outMXN.setText("Peso mexicano (MXN)");
        outMXN.setActionCommand("MXN");

        buttonGroupOut.add(outUSD);
        outUSD.setText("Dólar estadounidense (USD)");
        outUSD.setActionCommand("USD");

        buttonGroupOut.add(outEUR);
        outEUR.setText("Euro (EUR)");
        outEUR.setActionCommand("EUR");

        buttonGroupOut.add(outGBP);
        outGBP.setText("Libra esterlina (GBP)");
        outGBP.setActionCommand("GBP");

        buttonGroupOut.add(outJPY);
        outJPY.setText("Yen japonés (JPY)");
        outJPY.setActionCommand("JPY");

        buttonGroupOut.add(outKRW);
        outKRW.setText("Won surcoreano (KRW)");
        outKRW.setActionCommand("KRW");

        javax.swing.GroupLayout monedaTabLayout = new javax.swing.GroupLayout(monedaTab);
        monedaTab.setLayout(monedaTabLayout);
        monedaTabLayout.setHorizontalGroup(
                monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(monedaTabLayout.createSequentialGroup()
                                .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(monedaTabLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(monedaTabLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(inUSD, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(inEUR, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(inGBP, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(inJPY, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(inKRW, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(inMXN, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addGap(30, 30, 30)
                                .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(outMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(monedaTabLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(monedaTabLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(outMXN, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(outUSD, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(outEUR, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(outGBP, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(outJPY, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(outKRW, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addGap(30, 30, 30)
                                .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monedaTabLayout
                                                .createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(conversionMonedaButon,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addComponent(resultadoMonedaLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(conversionMonedaLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
        monedaTabLayout.setVerticalGroup(
                monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(monedaTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(monedaTabLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(outMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(conversionMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(monedaTabLayout.createSequentialGroup()
                                                .addComponent(resultadoMonedaLabel,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(conversionMonedaButon,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(monedaTabLayout.createSequentialGroup()
                                                .addGroup(monedaTabLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(inMXN)
                                                        .addComponent(outMXN))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(monedaTabLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(inUSD)
                                                        .addComponent(outUSD))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(monedaTabLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(inEUR)
                                                        .addComponent(outEUR))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(monedaTabLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(inGBP)
                                                        .addComponent(outGBP))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(monedaTabLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(inJPY, javax.swing.GroupLayout.PREFERRED_SIZE, 21,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(outJPY))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(monedaTabLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(inKRW)
                                                        .addComponent(outKRW))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        monedaTabLayout.linkSize(javax.swing.SwingConstants.VERTICAL,
                new java.awt.Component[] { conversionMonedaLabel, inMonedaLabel, outMonedaLabel });

        tabPanel.addTab("Moneda", monedaTab);

        inLongLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inLongLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inLongLabel.setText("Longitud origen");

        outLongLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outLongLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outLongLabel.setText("Longitud destino");

        conversionLongLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionLongLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conversionLongLabel.setText("Conversión");

        resultadoLongLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        resultadoLongLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoLongLabel.setText("0.00");

        conversionLongButon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionLongButon.setText("Convertir");

        javax.swing.GroupLayout longTabLayout = new javax.swing.GroupLayout(longTab);
        longTab.setLayout(longTabLayout);
        longTabLayout.setHorizontalGroup(
                longTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(longTabLayout.createSequentialGroup()
                                .addComponent(inLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(outLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(longTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resultadoLongLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(conversionLongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200,
                                                Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, longTabLayout
                                                .createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(conversionLongButon, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap()))));
        longTabLayout.setVerticalGroup(
                longTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(longTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(longTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(outLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(conversionLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conversionLongButon, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE)));

        tabPanel.addTab("Longitud", longTab);

        inAreaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inAreaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inAreaLabel.setText("Área origen");

        outAreaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outAreaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outAreaLabel.setText("Área destino");

        conversionAreaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionAreaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conversionAreaLabel.setText("Conversión");

        resultadoAreaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        resultadoAreaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoAreaLabel.setText("0.00");

        conversionAreaButon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionAreaButon.setText("Convertir");

        javax.swing.GroupLayout areaTabLayout = new javax.swing.GroupLayout(areaTab);
        areaTab.setLayout(areaTabLayout);
        areaTabLayout.setHorizontalGroup(
                areaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(areaTabLayout.createSequentialGroup()
                                .addComponent(inAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(outAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(areaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resultadoAreaLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(conversionAreaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200,
                                                Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaTabLayout
                                                .createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(conversionAreaButon, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap()))));
        areaTabLayout.setVerticalGroup(
                areaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(areaTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(areaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(outAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(conversionAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conversionAreaButon, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE)));

        tabPanel.addTab("Área", areaTab);

        inVolLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inVolLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inVolLabel.setText("Volumen origen");

        outVolLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outVolLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outVolLabel.setText("Volumen destino");

        conversionVolLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionVolLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conversionVolLabel.setText("Conversión");

        resultadoVolLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        resultadoVolLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoVolLabel.setText("0.00");

        conversionVolButon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionVolButon.setText("Convertir");

        javax.swing.GroupLayout volTabLayout = new javax.swing.GroupLayout(volTab);
        volTab.setLayout(volTabLayout);
        volTabLayout.setHorizontalGroup(
                volTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(volTabLayout.createSequentialGroup()
                                .addComponent(inVolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(outVolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(volTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resultadoVolLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(conversionVolLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200,
                                                Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, volTabLayout
                                                .createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(conversionVolButon, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap()))));
        volTabLayout.setVerticalGroup(
                volTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(volTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(volTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inVolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(outVolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(conversionVolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoVolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conversionVolButon, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE)));

        tabPanel.addTab("Volumen", volTab);

        inVelLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inVelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inVelLabel.setText("Velocidad origen");

        outVelLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outVelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outVelLabel.setText("Velocidad destino");

        conversionVelLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionVelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conversionVelLabel.setText("Conversión");

        resultadoVelLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        resultadoVelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoVelLabel.setText("0.00");

        conversionVelButon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionVelButon.setText("Convertir");

        javax.swing.GroupLayout velTabLayout = new javax.swing.GroupLayout(velTab);
        velTab.setLayout(velTabLayout);
        velTabLayout.setHorizontalGroup(
                velTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(velTabLayout.createSequentialGroup()
                                .addComponent(inVelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(outVelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(velTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resultadoVelLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(conversionVelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200,
                                                Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, velTabLayout
                                                .createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(conversionVelButon, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap()))));
        velTabLayout.setVerticalGroup(
                velTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(velTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(velTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inVelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(outVelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(conversionVelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoVelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conversionVelButon, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE)));

        tabPanel.addTab("Velocidad", velTab);

        inTempLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inTempLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inTempLabel.setText("Temperatura origen");

        outTempLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outTempLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outTempLabel.setText("Temperatura destino");

        conversionTempLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionTempLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conversionTempLabel.setText("Conversión");

        resultadoTempLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        resultadoTempLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoTempLabel.setText("0.00");

        conversionTempButon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionTempButon.setText("Convertir");

        javax.swing.GroupLayout tempTabLayout = new javax.swing.GroupLayout(tempTab);
        tempTab.setLayout(tempTabLayout);
        tempTabLayout.setHorizontalGroup(
                tempTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tempTabLayout.createSequentialGroup()
                                .addComponent(inTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(outTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(tempTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resultadoTempLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(conversionTempLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200,
                                                Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tempTabLayout
                                                .createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(conversionTempButon, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap()))));
        tempTabLayout.setVerticalGroup(
                tempTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tempTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tempTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(outTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(conversionTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conversionTempButon, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE)));

        tabPanel.addTab("Temperatura", tempTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(inLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inText))
                                        .addComponent(tabPanel))
                                .addGap(30, 30, 30)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(inLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inText, javax.swing.GroupLayout.DEFAULT_SIZE, 60,
                                                Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tabPanel)
                                .addGap(30, 30, 30)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inTextMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_inTextMouseClicked
        inText.setText("");
    }// GEN-LAST:event_inTextMouseClicked

    private void conversionMonedaButonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_conversionMonedaButonActionPerformed
        String inMonedaTipo = buttonGroupIn.getSelection().getActionCommand();
        String outMonedaTipo = buttonGroupOut.getSelection().getActionCommand();
        String monto = inText.getText();

        if (inMonedaTipo == outMonedaTipo) {
            resultadoMonedaLabel.setText(monto);
        } else {
            try {
                Moneda inMoneda = new Moneda(inMonedaTipo);
                Moneda outMoneda = new Moneda(outMonedaTipo);
                String resultado = outMoneda.conversion(monto, inMoneda);

                resultadoMonedaLabel.setText(resultado);
            } catch (Exception exception) {
                if (monto.contains(",")) {
                    JOptionPane.showMessageDialog(new JFrame(), "Utilice punto decimal", "¡Alerta!",
                            JOptionPane.ERROR_MESSAGE);
                } else if (monto.contains(" ")) {
                    JOptionPane.showMessageDialog(new JFrame(), "No utilice espacios", "¡Alerta!",
                            JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Formato no válido", "¡Alerta!",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }// GEN-LAST:event_conversionMonedaButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaTab;
    private javax.swing.ButtonGroup buttonGroupIn;
    private javax.swing.ButtonGroup buttonGroupOut;
    private javax.swing.JButton conversionAreaButon;
    private javax.swing.JLabel conversionAreaLabel;
    private javax.swing.JButton conversionLongButon;
    private javax.swing.JLabel conversionLongLabel;
    private javax.swing.JButton conversionMonedaButon;
    private javax.swing.JLabel conversionMonedaLabel;
    private javax.swing.JButton conversionTempButon;
    private javax.swing.JLabel conversionTempLabel;
    private javax.swing.JButton conversionVelButon;
    private javax.swing.JLabel conversionVelLabel;
    private javax.swing.JButton conversionVolButon;
    private javax.swing.JLabel conversionVolLabel;
    private javax.swing.JLabel inAreaLabel;
    private javax.swing.JRadioButton inEUR;
    private javax.swing.JRadioButton inGBP;
    private javax.swing.JRadioButton inJPY;
    private javax.swing.JRadioButton inKRW;
    private javax.swing.JLabel inLabel;
    private javax.swing.JLabel inLongLabel;
    private javax.swing.JRadioButton inMXN;
    private javax.swing.JLabel inMonedaLabel;
    private javax.swing.JLabel inTempLabel;
    private javax.swing.JTextField inText;
    private javax.swing.JRadioButton inUSD;
    private javax.swing.JLabel inVelLabel;
    private javax.swing.JLabel inVolLabel;
    private javax.swing.JPanel longTab;
    private javax.swing.JPanel monedaTab;
    private javax.swing.JLabel outAreaLabel;
    private javax.swing.JRadioButton outEUR;
    private javax.swing.JRadioButton outGBP;
    private javax.swing.JRadioButton outJPY;
    private javax.swing.JRadioButton outKRW;
    private javax.swing.JLabel outLongLabel;
    private javax.swing.JRadioButton outMXN;
    private javax.swing.JLabel outMonedaLabel;
    private javax.swing.JLabel outTempLabel;
    private javax.swing.JRadioButton outUSD;
    private javax.swing.JLabel outVelLabel;
    private javax.swing.JLabel outVolLabel;
    private javax.swing.JLabel resultadoAreaLabel;
    private javax.swing.JLabel resultadoLongLabel;
    private javax.swing.JLabel resultadoMonedaLabel;
    private javax.swing.JLabel resultadoTempLabel;
    private javax.swing.JLabel resultadoVelLabel;
    private javax.swing.JLabel resultadoVolLabel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JPanel tempTab;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JPanel velTab;
    private javax.swing.JPanel volTab;
    // End of variables declaration//GEN-END:variables
}
