/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.interfase;

import com.conversor.model.Moneda;
import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UIManager;

/**
 *
 * @author nigeh
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupIn = new javax.swing.ButtonGroup();
        buttonGroupOut = new javax.swing.ButtonGroup();
        tituloLabel = new javax.swing.JLabel();
        inLabel = new javax.swing.JLabel();
        inText = new javax.swing.JTextField();
        tabPanel = new javax.swing.JTabbedPane();
        monedaTab = new javax.swing.JPanel();
        inMonedaLabel = new javax.swing.JLabel();
        outMonedaLabel = new javax.swing.JLabel();
        conversionMonedaLabel = new javax.swing.JLabel();
        resultadoMonedaLabel = new javax.swing.JLabel();
        conversionMonedaButon = new javax.swing.JButton();
        inMXN = new javax.swing.JRadioButton();
        inUSD = new javax.swing.JRadioButton();
        inEUR = new javax.swing.JRadioButton();
        inGBP = new javax.swing.JRadioButton();
        inJPY = new javax.swing.JRadioButton();
        inKRW = new javax.swing.JRadioButton();
        outMXN = new javax.swing.JRadioButton();
        outUSD = new javax.swing.JRadioButton();
        outEUR = new javax.swing.JRadioButton();
        outGBP = new javax.swing.JRadioButton();
        outJPY = new javax.swing.JRadioButton();
        outKRW = new javax.swing.JRadioButton();
        longTab = new javax.swing.JPanel();
        inLongLabel = new javax.swing.JLabel();
        outLongLabel = new javax.swing.JLabel();
        conversionLongLabel = new javax.swing.JLabel();
        resultadoLongLabel = new javax.swing.JLabel();
        conversionLongButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ORDUS");
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Conversor");

        inLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        inLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inLabel.setText("Cantidad");

        inText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inText.setText("0.00");
        inText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inTextMouseClicked(evt);
            }
        });

        inMonedaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inMonedaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inMonedaLabel.setText("Moneda origen");

        outMonedaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outMonedaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outMonedaLabel.setText("Moneda destino");

        conversionMonedaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionMonedaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conversionMonedaLabel.setText("Conversión");

        resultadoMonedaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        resultadoMonedaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoMonedaLabel.setText("0.00");

        conversionMonedaButon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionMonedaButon.setText("Convertir");
        conversionMonedaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversionMonedaButonActionPerformed(evt);
            }
        });

        buttonGroupIn.add(inMXN);
        inMXN.setSelected(true);
        inMXN.setText("Peso mexicano (MXN)");
        inMXN.setActionCommand("MXN");

        buttonGroupIn.add(inUSD);
        inUSD.setText("Dólar estadounidense (USD)");
        inUSD.setActionCommand("USD");

        buttonGroupIn.add(inEUR);
        inEUR.setText("Euro (EUR)");
        inEUR.setActionCommand("EUR");

        buttonGroupIn.add(inGBP);
        inGBP.setText("Libra esterlina (GBP)");
        inGBP.setActionCommand("GBP");

        buttonGroupIn.add(inJPY);
        inJPY.setText("Yen japonés (JPY)");
        inJPY.setActionCommand("JPY");

        buttonGroupIn.add(inKRW);
        inKRW.setText("Won surcoreano (KRW)");
        inKRW.setActionCommand("KRW");

        buttonGroupOut.add(outMXN);
        outMXN.setSelected(true);
        outMXN.setText("Peso mexicano (MXN)");
        outMXN.setActionCommand("MXN");

        buttonGroupOut.add(outUSD);
        outUSD.setText("Dólar estadounidense (USD)");
        outUSD.setActionCommand("USD");

        buttonGroupOut.add(outEUR);
        outEUR.setText("Euro (EUR)");
        outEUR.setActionCommand("EUR");

        buttonGroupOut.add(outGBP);
        outGBP.setText("Libra esterlina (GBP)");
        outGBP.setActionCommand("GBP");

        buttonGroupOut.add(outJPY);
        outJPY.setText("Yen japonés (JPY)");
        outJPY.setActionCommand("JPY");

        buttonGroupOut.add(outKRW);
        outKRW.setText("Won surcoreano (KRW)");
        outKRW.setActionCommand("KRW");

        javax.swing.GroupLayout monedaTabLayout = new javax.swing.GroupLayout(monedaTab);
        monedaTab.setLayout(monedaTabLayout);
        monedaTabLayout.setHorizontalGroup(
            monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monedaTabLayout.createSequentialGroup()
                .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(monedaTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inUSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inEUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inGBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inJPY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inKRW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inMXN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(monedaTabLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(outMXN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outUSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outEUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outGBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outJPY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outKRW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monedaTabLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(conversionMonedaButon, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(resultadoMonedaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conversionMonedaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        monedaTabLayout.setVerticalGroup(
            monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monedaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conversionMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monedaTabLayout.createSequentialGroup()
                        .addComponent(resultadoMonedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conversionMonedaButon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(monedaTabLayout.createSequentialGroup()
                        .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inMXN)
                            .addComponent(outMXN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inUSD)
                            .addComponent(outUSD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inEUR)
                            .addComponent(outEUR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inGBP)
                            .addComponent(outGBP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inJPY, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outJPY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(monedaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inKRW)
                            .addComponent(outKRW))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        monedaTabLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {conversionMonedaLabel, inMonedaLabel, outMonedaLabel});

        tabPanel.addTab("Moneda", monedaTab);

        inLongLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inLongLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inLongLabel.setText("Longitud origen");

        outLongLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outLongLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outLongLabel.setText("Longitud destino");

        conversionLongLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionLongLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conversionLongLabel.setText("Conversión");

        resultadoLongLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        resultadoLongLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoLongLabel.setText("0.00");

        conversionLongButon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conversionLongButon.setText("Convertir");

        javax.swing.GroupLayout longTabLayout = new javax.swing.GroupLayout(longTab);
        longTab.setLayout(longTabLayout);
        longTabLayout.setHorizontalGroup(
            longTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(longTabLayout.createSequentialGroup()
                .addComponent(inLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(outLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(longTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultadoLongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conversionLongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, longTabLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(conversionLongButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        longTabLayout.setVerticalGroup(
            longTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(longTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(longTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conversionLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultadoLongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conversionLongButon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tabPanel.addTab("Longitud", longTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inText))
                    .addComponent(tabPanel))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inText, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabPanel)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inTextMouseClicked
        inText.setText("");
    }//GEN-LAST:event_inTextMouseClicked

    private void conversionMonedaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversionMonedaButonActionPerformed
        String inMonedaTipo = buttonGroupIn.getSelection().getActionCommand();
        String outMonedaTipo = buttonGroupOut.getSelection().getActionCommand();
        String monto = inText.getText();

        if (inMonedaTipo == outMonedaTipo) {
            resultadoMonedaLabel.setText(monto);
        } else {
            try {
                Moneda inMoneda = new Moneda(inMonedaTipo);
                Moneda outMoneda = new Moneda(outMonedaTipo);
                String resultado = outMoneda.conversion(monto, inMoneda);
                
                resultadoMonedaLabel.setText(resultado);
            } catch (Exception e) {
                e.getStackTrace();
            }
        }
    }//GEN-LAST:event_conversionMonedaButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupIn;
    private javax.swing.ButtonGroup buttonGroupOut;
    private javax.swing.JButton conversionLongButon;
    private javax.swing.JLabel conversionLongLabel;
    private javax.swing.JButton conversionMonedaButon;
    private javax.swing.JLabel conversionMonedaLabel;
    private javax.swing.JRadioButton inEUR;
    private javax.swing.JRadioButton inGBP;
    private javax.swing.JRadioButton inJPY;
    private javax.swing.JRadioButton inKRW;
    private javax.swing.JLabel inLabel;
    private javax.swing.JLabel inLongLabel;
    private javax.swing.JRadioButton inMXN;
    private javax.swing.JLabel inMonedaLabel;
    private javax.swing.JTextField inText;
    private javax.swing.JRadioButton inUSD;
    private javax.swing.JPanel longTab;
    private javax.swing.JPanel monedaTab;
    private javax.swing.JRadioButton outEUR;
    private javax.swing.JRadioButton outGBP;
    private javax.swing.JRadioButton outJPY;
    private javax.swing.JRadioButton outKRW;
    private javax.swing.JLabel outLongLabel;
    private javax.swing.JRadioButton outMXN;
    private javax.swing.JLabel outMonedaLabel;
    private javax.swing.JRadioButton outUSD;
    private javax.swing.JLabel resultadoLongLabel;
    private javax.swing.JLabel resultadoMonedaLabel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
